import AsyncStorage from '@react-native-async-storage/async-storage';
import { AppLicense, LicenseValidationResult } from '../types';

const STORAGE_KEYS = {
  LICENSE: '@puerflix_license',
  DEVICE_ID: '@puerflix_device_id',
};

// Official master & promo keys for initial deployment and testing
const MASTER_KEYS: Record<string, { planName: string; maxDevices: number }> = {
  'PUER-VIP-2026-PAIS': { planName: 'Plano Fundador Vitalício', maxDevices: 5 },
  'PUER-DEMO-KIDS-SAFE': { planName: 'Acesso Demonstração Familiar', maxDevices: 3 },
  'PUER-TEST-9999-BETA': { planName: 'Licença Beta Tester', maxDevices: 1 },
  'PUER-BRUNO-PRO-2026': { planName: 'Licença Master Administrador', maxDevices: 10 },
};

/**
 * Validates algorithmic checksum for keys generated by checkout webhooks
 * Format: PUER-XXXX-YYYY-ZZZZ where checksum byte matches
 */
function verifyKeyChecksum(cleanKey: string): boolean {
  if (MASTER_KEYS[cleanKey]) {
    return true;
  }

  // Must start with PUER-
  if (!cleanKey.startsWith('PUER-')) {
    return false;
  }

  const parts = cleanKey.split('-');
  if (parts.length !== 4) {
    return false;
  }

  // Basic structure: PUER-XXXX-XXXX-XXXX (each block 4 alphanumeric chars)
  for (let i = 1; i < parts.length; i++) {
    if (parts[i].length !== 4 || !/^[A-Z0-9]+$/.test(parts[i])) {
      return false;
    }
  }

  // Algorithmic parity check across blocks
  const b1 = parts[1];
  const b2 = parts[2];
  const b3 = parts[3];

  let sum = 0;
  for (let i = 0; i < 4; i++) {
    sum += b1.charCodeAt(i) * 3 + b2.charCodeAt(i) * 7;
  }
  const expectedCheckHex = (sum % 256).toString(16).toUpperCase().padStart(2, '0');
  
  // The last 2 characters of b3 are the checksum signature
  const keyCheck = b3.slice(-2);
  return keyCheck === expectedCheckHex;
}

/**
 * Generates a valid customer key matching the verification algorithm.
 * Used by checkout generators and backend webhooks.
 */
export function generateValidLicenseKey(prefixSeed: string = 'KIDS'): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // No ambiguous characters (O, 0, I, 1)
  let b1 = '';
  let b2 = '';
  for (let i = 0; i < 4; i++) {
    b1 += chars.charAt(Math.floor(Math.random() * chars.length));
    b2 += chars.charAt(Math.floor(Math.random() * chars.length));
  }

  let sum = 0;
  for (let i = 0; i < 4; i++) {
    sum += b1.charCodeAt(i) * 3 + b2.charCodeAt(i) * 7;
  }
  const expectedCheckHex = (sum % 256).toString(16).toUpperCase().padStart(2, '0');
  
  const b3FirstTwo = chars.charAt(Math.floor(Math.random() * chars.length)) + chars.charAt(Math.floor(Math.random() * chars.length));
  const b3 = b3FirstTwo + expectedCheckHex;

  return `PUER-${b1}-${b2}-${b3}`;
}

export const LicenseService = {
  /**
   * Retrieves or creates a persistent device ID unique to this Android hardware / browser install
   */
  async getDeviceId(): Promise<string> {
    try {
      let id = await AsyncStorage.getItem(STORAGE_KEYS.DEVICE_ID);
      if (!id) {
        const randomPart = Math.random().toString(36).substring(2, 9).toUpperCase();
        const timestamp = Date.now().toString(36).toUpperCase();
        id = `DVC-${timestamp}-${randomPart}`;
        await AsyncStorage.setItem(STORAGE_KEYS.DEVICE_ID, id);
      }
      return id;
    } catch {
      return 'DVC-DEFAULT-001';
    }
  },

  /**
   * Retrieves currently stored license record
   */
  async getStoredLicense(): Promise<AppLicense | null> {
    try {
      const data = await AsyncStorage.getItem(STORAGE_KEYS.LICENSE);
      if (!data) return null;
      const license: AppLicense = JSON.parse(data);
      return license;
    } catch {
      return null;
    }
  },

  /**
   * Checks if app is currently licensed on this device
   */
  async isAppLicensed(): Promise<boolean> {
    const license = await this.getStoredLicense();
    if (!license || !license.isLicensed) return false;

    // Check expiration if applicable (null means lifetime)
    if (license.expiresAt && Date.now() > license.expiresAt) {
      return false;
    }

    return true;
  },

  /**
   * Validates and activates a license key for this device
   */
  async activateLicense(
    inputKey: string,
    customerEmail?: string
  ): Promise<LicenseValidationResult> {
    try {
      const cleanKey = inputKey
        .trim()
        .toUpperCase()
        .replace(/\s+/g, '');

      if (!cleanKey) {
        return {
          valid: false,
          message: 'Por favor, digite a sua chave de ativação.',
        };
      }

      // 1. Verify format & checksum signature
      const isValid = verifyKeyChecksum(cleanKey);
      if (!isValid) {
        return {
          valid: false,
          message:
            'Chave de ativação inválida ou não reconhecida. Verifique se digitou todos os dígitos corretamente (ex: PUER-XXXX-XXXX-XXXX).',
        };
      }

      // 2. Fetch device identity
      const deviceId = await this.getDeviceId();
      const planMeta = MASTER_KEYS[cleanKey] || {
        planName: 'Plano Acesso Familiar Seguro',
        maxDevices: 2,
      };

      // 3. Construct activated license record
      const license: AppLicense = {
        isLicensed: true,
        licenseKey: cleanKey,
        deviceId,
        activatedAt: Date.now(),
        customerEmail: customerEmail?.trim().toLowerCase(),
        planName: planMeta.planName,
        maxDevices: planMeta.maxDevices,
        expiresAt: null, // Lifetime / active subscription
      };

      // 4. Save to persistent storage
      await AsyncStorage.setItem(STORAGE_KEYS.LICENSE, JSON.stringify(license));

      return {
        valid: true,
        license,
        message: '🎉 Licença ativada com sucesso neste dispositivo!',
      };
    } catch (e: any) {
      return {
        valid: false,
        message: `Falha ao registrar a licença: ${e.message || 'Erro inesperado'}`,
      };
    }
  },

  /**
   * Deactivates license on this device
   */
  async deactivateLicense(): Promise<void> {
    try {
      await AsyncStorage.removeItem(STORAGE_KEYS.LICENSE);
    } catch (e) {
      console.error('Error deactivating license:', e);
    }
  },
};
